### ISSUE TITLE
Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by fess56rus** [Sharrnah/whispering#11]
![Clip2Net DropZone_230410170816](https://user-images.githubusercontent.com/40686071/230898860-2a72635e-f91d-4ed5-87c1-ba3ece823221.png)

**Comment by Sharrnah** [comment]
Sorry for the late reply.
Did you try installing it in a clean virtual python environment?

Could be that you installed it in a python environment with some incompatible versions. (maybe the websockets library that for some reason sends bytes instead of json string in some newer or older version?
In the standalone it should use the (as of this writing) newest websocket library (v11.0.3)

If you only try to run the project, you can try the standalone build from the releases, then you won't need to install all dependencies yourself.
also are you running it with the UI (https://github.com/Sharrnah/whispering-ui) or without it?

I actually haven't tried it running without the UI for some time now, 
So could be that i just broke something when running without the UI. 👀

**Comment by Sharrnah** [comment]
will close this for now. Feel free to open again if you need any more help.
