### ISSUE TITLE
Faster Whisper (CTranslate2) Support

### ISSUE THREAD

**Issue by Infinitay** [Sharrnah/whispering#7]
https://github.com/guillaumekln/faster-whisper/

> This implementation is up to 4 times faster than [openai/whisper](https://github.com/openai/whisper) for the same accuracy while using less memory

I would assume we'd greatly benefit from the improved performance since we're working with live translating

**Comment by Sharrnah** [comment]
thanks. this is now integrated and possible to activate in the UI (or setting `faster_whisper: true` in the config yaml)

![grafik](https://user-images.githubusercontent.com/55756126/224575344-f9cd7713-f459-44de-b11d-9a3c9acae0e6.png)

**Comment by Infinitay** [comment]
Honestly I was not expecting support for this, thank you so much. I'm looking forward to testing and using this soon. Hopefully I can finally run the large whisper model and get better results.

**Comment by Sharrnah** [comment]
thanks. Yes its so much faster in my testings that i could not not implement it. :)

Another setting i noticed that can help a bit more in speeding up translations or transcriptions is disabling `temperature_fallback`. I added that option in the last update as well.

I moved it to advanced because it can reduce the quality since it only does a single iteration even if the A.I. isn't perfectly confident about the result, and the CTranslate2 version is possibly still fast enough.

![grafik](https://user-images.githubusercontent.com/55756126/224575924-57a30b1c-6d8c-4bf2-8d0e-736b6c16be06.png)
